export type Locale = 'pt-BR' | 'en'

export const translations = {
  'pt-BR': {
    metaTitle: 'Jorge Mesquita | Desenvolvedor de sistemas',
    metaDescription: 'Portfólio digital de Jorge Mesquita: code, data, design, automation e systems.',
    nav: { work: 'Trabalho', system: 'Sistema', process: 'Processo', about: 'Sobre', contact: 'Contato' },
    hero: { eyebrow: 'Disponível para criar', title: 'Ideias que\nganham sistema.', intro: 'Sou Jorge Mesquita, estudante de Análise e Desenvolvimento de Sistemas e desenvolvedor interessado na interseção entre código, dados, design e automação.', cta: 'Explorar trabalho', location: 'Recife, BR', scroll: 'Scroll para descobrir', artifact: 'artefato generativo / 001' },
    work: { label: '02 / 06', title: 'Selected\nwork.', note: 'Projetos como estudos de caso — da pergunta inicial ao resultado.', dash: { type: 'Case study / Data systems', title: 'DASH DIGITAL', description: 'Estrutura preparada para documentar um projeto real: coleta, transformação, análise e entrega de dados.', problem: 'Problema', system: 'Sistema', implementation: 'Implementação', decisions: 'Decisões', technology: 'Tecnologia', testing: 'Testes', deployment: 'Deploy', result: 'Resultado', pipeline: ['Data collection', 'ETL', 'Analysis', 'Frontend', 'Testing', 'CI/CD', 'Deployment'], status: 'Conteúdo em construção' } },
    system: { label: '03 / 06', title: 'A whole\nsystem.', note: 'As disciplinas não vivem em silos. Elas criam valor quando conversam.', hint: 'Selecione um núcleo para explorar', details: { Code: 'Lógica, interfaces e software que resolvem problemas.', Data: 'Coleta, estrutura e leitura de informação.', Design: 'Clareza visual, interação e intenção.', Automation: 'Fluxos que reduzem fricção e trabalho repetitivo.', Systems: 'Relações, restrições e decisões de arquitetura.' } },
    process: { label: '04 / 06', title: 'From problem\nto product.', steps: [['01', 'Observe', 'Entender o contexto antes de tocar na solução.'], ['02', 'Define', 'Encontrar relações, restrições e oportunidades.'], ['03', 'Design', 'Dar forma à experiência e ao sistema.'], ['04', 'Build', 'Prototipar com intenção e código.'], ['05', 'Test', 'Verificar comportamento, acessibilidade e limites.'], ['06', 'Debug', 'Investigar causas, não apenas sintomas.'], ['07', 'Iterate', 'Refinar a partir de evidências.'], ['08', 'Deploy', 'Entregar algo que continua fazendo sentido.']] },
    about: { label: '05 / 06', title: 'A curious\nbuilder.', profile: 'Perfil', copy: 'Ainda estou no começo, mas nunca estive parado. Minha formação em Análise e Desenvolvimento de Sistemas é o ponto de partida para construir coisas úteis, bonitas e bem pensadas.', education: 'Formação', educationValue: 'Análise e Desenvolvimento de Sistemas', courses: 'Cursos', coursesValue: 'A adicionar — conteúdo real em atualização.', skills: 'Habilidades', skillsValue: 'Code · Data · Design · Automation · Systems' },
    contact: { label: '06 / 06', title: 'Vamos criar\nalgo vivo.', copy: 'Contato profissional', email: '[seu-email-profissional@exemplo.com]', footer: 'Feito com intenção.', top: 'Voltar ao topo' },
    language: 'Idioma', menu: 'Abrir menu', close: 'Fechar menu', artifactAlt: 'Visualização generativa composta por caracteres, que reage ao movimento e ao scroll.'
  },
  en: {
    metaTitle: 'Jorge Mesquita | Systems developer', metaDescription: 'Digital portfolio by Jorge Mesquita: code, data, design, automation and systems.',
    nav: { work: 'Work', system: 'System', process: 'Process', about: 'About', contact: 'Contact' },
    hero: { eyebrow: 'Available to create', title: 'Ideas that\nbecome systems.', intro: 'I am Jorge Mesquita, an Analysis and Systems Development student interested in the intersection of code, data, design and automation.', cta: 'Explore work', location: 'Recife, BR', scroll: 'Scroll to discover', artifact: 'generative artifact / 001' },
    work: { label: '02 / 06', title: 'Selected\nwork.', note: 'Projects as case studies — from the first question to the outcome.', dash: { type: 'Case study / Data systems', title: 'DASH DIGITAL', description: 'A structure prepared to document a real project: data collection, transformation, analysis and delivery.', problem: 'Problem', system: 'System', implementation: 'Implementation', decisions: 'Decisions', technology: 'Technology', testing: 'Testing', deployment: 'Deployment', result: 'Result', pipeline: ['Data collection', 'ETL', 'Analysis', 'Frontend', 'Testing', 'CI/CD', 'Deployment'], status: 'Content in progress' } },
    system: { label: '03 / 06', title: 'A whole\nsystem.', note: 'Disciplines do not live in silos. They create value when they connect.', hint: 'Select a node to explore', details: { Code: 'Logic, interfaces and software that solve problems.', Data: 'Collection, structure and reading of information.', Design: 'Visual clarity, interaction and intention.', Automation: 'Flows that reduce friction and repetitive work.', Systems: 'Relationships, constraints and architecture decisions.' } },
    process: { label: '04 / 06', title: 'From problem\nto product.', steps: [['01', 'Observe', 'Understand the context before touching the solution.'], ['02', 'Define', 'Find relationships, constraints and opportunities.'], ['03', 'Design', 'Shape the experience and the system.'], ['04', 'Build', 'Prototype with intention and code.'], ['05', 'Test', 'Verify behavior, accessibility and limits.'], ['06', 'Debug', 'Investigate causes, not only symptoms.'], ['07', 'Iterate', 'Refine from evidence.'], ['08', 'Deploy', 'Ship something that keeps making sense.']] },
    about: { label: '05 / 06', title: 'A curious\nbuilder.', profile: 'Profile', copy: 'I am still at the beginning, but never standing still. My degree in Analysis and Systems Development is the starting point for building things that are useful, beautiful and well-considered.', education: 'Education', educationValue: 'Analysis and Systems Development', courses: 'Courses', coursesValue: 'To be added — real content being updated.', skills: 'Skills', skillsValue: 'Code · Data · Design · Automation · Systems' },
    contact: { label: '06 / 06', title: 'Let’s create\nsomething alive.', copy: 'Professional contact', email: '[your-professional-email@example.com]', footer: 'Made with intention.', top: 'Back to top' },
    language: 'Language', menu: 'Open menu', close: 'Close menu', artifactAlt: 'Generative character visualization that responds to movement and scroll.'
  }
} as const

export type Copy = typeof translations['pt-BR']
export const getCopy = (locale: Locale): Copy => translations[locale]
